[package]
name = "zoma-cmd"
version = "0.1.0"
authors = ["Vuraddo <vuraddo@yahoo.com>"]

[dependencies]

[[bin]]
name = "provider"
path = "provider/src/main.rs"

[[bin]]
name = "client"
path = "client/src/main.rs"

[workspace]
members = [
    "provider",
    "client",
]
